<?php

use Drupal\Core\Routing\RouteMatchInterface;

/** Implements hook_help()
*
*/

function second_module_help($route_name, RouteMatchInterface $route_match){

    switch ($route_name){
        case 'help.page.second_module':
        $output = '';
        $output .='<h3>'.t('About').'</h3>';
        $output .= '<p>'.t('This is second help hook for custome module.').'</p>';

        return $output;
        default;

    }
}
