_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 5e4dbdbe-5379-4112-a4a9-01f637287b8b
name: 'Hello Drupal!'
mail: admin@example.com
slogan: 'Awesome platform'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
